interface ArtDisplayInfo {
  auction_site: string;
  auction_url_num: number;
  auction_place: string;
  auction_date: string;
  artist_name_kor: string;
  artist_name_eng:string;
  artist_comment:string;
  lot_no:number;
  make_year:string;
  title_kor:string;
  title_eng:string;
  currency:string;
  money:number;
  unit_cd:string;
  size_length:number;
  size_width:number;
  mix_cd:string;
  mix_size:number;
  canvas:number;
  medium_eng:string;
  medium_kor:string;
  description:string;
  estimate_high:number;
  estimate_low:number;
  edition:string;
  image_name:string;
  image_url:string;
};
